### ISSUE TITLE
error when adding fess-ds-atlassian-12.2.0.jar on docker fess

### ISSUE THREAD

**Issue by thesoul214** [codelibs/docker-fess#12]
Hello. 

I am using fess with docker version (FROM codelibs/fess:latest)

when I restart fess after I locate fess-ds-atlassian-12.2.0.jar file into /usr/share/fess/app/WEB-INF/lib inside of docker fess, I got some error like attached file.

do I need to run some kind of command after I locate jar file.

please let me know the solution.

Thanks 
[att_error.log](https://github.com/codelibs/docker-fess/files/2458978/att_error.log)

**Comment by marevol** [comment]
You need to use Fess 12.2 or the above.

**Comment by thesoul214** [comment]
> You need to use Fess 12.2 or the above.

Thanks! I resolved it!
