### ISSUE TITLE
Permissions with externalized logs file

### ISSUE THREAD

**Issue by cernadasjuan** [codelibs/docker-fess#2]
Hi,

I tried to link the logs folder to an external volume, so I can have them in my filesystem. But when I do that, the owner of the files is the "root" user, Is there any way to configure this user? With the official ElasticSearch image, there is no problem with that.

Thanks!

**Comment by nullpos** [comment]
Please update containers from Dockerhub and try this.
- Create a directory which you want to link with container before starting container.
or
- Change directory permission on your filesystem to 1000:1000 and restart container.
example:
`$ chmod -R 1000:1000 /path/to/log`

**Comment by cernadasjuan** [comment]
Thanks!!!!!!!!
