### ISSUE TITLE
Externalized data and log issues

### ISSUE THREAD

**Issue by bmcdavid** [codelibs/docker-fess#4]
I'm trying to use the attached docker-compose file [docker-compose.yml.txt](https://github.com/codelibs/docker-fess/files/919928/docker-compose.yml.txt) and have some issues.

First, I need to create the folders before starting the container and run the chown -R 1000:1000 on the mapped volumes.

Second, a restart on the container fails, and the only way to get it running again is to delete the es-data mapped volume and recreate and change the owner again.

I would like to be able use this setup to persist the data, so I can update FESS without data loss.

Also, I'm testing on Docker 17.03.1-ce build c6d412e on an Ubuntu 16.04.2 server.

Any suggestions?

Thanks,
Brad

**Comment by nullpos** [comment]
Any logs? I tested and find this error.
`java.lang.IllegalArgumentException: IOException while reading keywords_path: /opt/fess/es/config/node_1/ar/protwords.txt`
Fess uses the dictionary files in `/opt/fess/es/config/*`. So I think you should add this directory to volumes.

**Comment by bmcdavid** [comment]
Thanks, that helped get it running as I expected.
