### ISSUE TITLE
Errors on latest Dockerfile?

### ISSUE THREAD

**Issue by vitorcoxta** [codelibs/docker-fess#5]
Hi,

I'm using the fess image on a project, however the latest is not running up correctly... I'm getting the following error:

`Caused by: org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{d-BjrzUnSU665QsHHz9Nlw}{localhost}{127.0.0.1:9300}]`

I am running the image as stated on the docker hub page:

`$ docker run -d -p 8080:8080 --name fess codelibs/fess:latest`

Is this error known, or am I doing something wrong? I'm considering using the tag 11.1, although it has "unrecommended" on the docker hub... Why is it unrecommended, by the way?

Thank you

**Comment by bluelink8888** [comment]
I believe its x-pack problem.
Actually codelibs all project didn't consider x-pack plugin problem, 
and its es version is 5.5.2 will install x-pack. 
maybe u can try add remove plugin in Dockerfile and try again.

`RUN /usr/share/elasticsearch/bin/elasticsearch-plugin remove x-pack`
add this into Dockerfile should remove x-pack plugin

**Comment by jimmyhung8888** [comment]
@marevol 
Hello, i have try this issue in my custom docker file. 
I was found 9300 will bound to 172.17.0.2:9300, it won't bound localhost.
hope this can help u.

**Comment by marevol** [comment]
Docker images were updated.
So, this issue should be disappeared.
If you have any problems, please file a new issue with details.
